version: '3.8'

services:
  # MongoDB 資料庫
  mongodb:
    image: mongo:7.0
    container_name: sortify_mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: unless-stopped

  # Sortify 後端服務
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sortify_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data/chromadb:/app/data/chromadb
      - ./uploaded_files:/app/uploaded_files
    environment:
      - MONGODB_URL=mongodb://admin:password@mongodb:27017
      - DB_NAME=sortify_db
      # 其他環境變數在 .env 檔案中配置
    depends_on:
      - mongodb
    restart: unless-stopped

  # 前端服務
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sortify_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped 